#!/bin/bash
## Puts files in a trash folder instead of deleting them ##

delete=false
recursive=true
verbose=false
prompt=false
alert=false

trash=~/.local/share/Trash/files
optionName=
argIsValue=false
FILES=""
skip=false

display()
{
	if $verbose; then
		echo "$*"
	fi
}

prompt()
{
	read -p "Remove $1 ? " answer

	case $answer in
		no) display "Skipping $1"; skip=true;;
		yes) skip=false;;
		*)
			while [ $answer != "yes" ] && [ $answer != "no" ]
			do
				read -p "Please answer 'yes' or 'no'" answer
			done

			case $answer in
				no) display "Skipping $1"; skip=true;;
				yes) skip=false;;
			esac
	esac
}

if [ ! -d $trash ]; then
	mkdir -p $trash
	chmod 700 $trash
fi

for arg in "$@"
do
	case $arg in
		-*)optionName="$(echo $arg|sed s/"^-"//)";
			for letter in $(seq 1 ${#optionName})
			do
				option=$(echo $optionName|cut -c $letter)

				case $option in
					i) prompt=true;;
					I) alert=true;;
					n) recursive=false;;
					d) delete=true;;
					v) verbose=true;;
					*) echo "Invalid option $option" 1>&2;;
			esac
			done
		;;
		*) FILES="${FILES}$arg "
		;;
	esac
done

nb="$(echo $FILES|wc -w)"

if $alert && [ $nb -gt 3 ]; then
	read -p "You are about to remove $nb files. Continue ? " answer
	case $answer in
		no) display "Aborted"; exit;;
		yes) display "Proceeding...";;
		*) while [ "$answer" != "yes" ] && [ "$answer" != "no" ]; do read -p "Please answer 'yes' or 'no': "; done;
			case $answer in
				no) display "Aborted"; exit;;
				yes) display "Proceeding...";;
			esac
	esac
fi

for file in $FILES
do
	timestamp=$(date +%d%m%Y_%T)
	trashName="$(basename $file)_$timestamp"
	counter=2

	while [ -e $trash/$trashName ]
	do
		trashName="$trashName_$counter"
		counter=$((counter + 1))
	done


	if $prompt; then
		prompt $file
		if $skip; then continue; fi
	fi

	if [ -d $file ] && ! $recursive; then
		echo "Error: $file is directory and recursion is off" 1>&2
		continue
	fi

	if $delete; then
		if ! $recursive; then rm $file; else rm -r $file; fi
		display "Removed $file"
		continue
	fi

	mv $file "$trash/$trashName" && display "Removed $file"
done
